import type { CategorySlug } from '../config/categories';
import { contentCategoryPath } from './content-categories';

export const ABOUT_PATH = '/info/about';
export const HELP_PATH = '/info/help';
export const LICENSE_PATH = '/info/license';
export const TERMS_PATH = '/info/terms';
export const PRIVACY_PATH = '/info/privacy';
export const COOKIES_PATH = '/info/cookies';
export const REFUNDS_PATH = '/info/refunds';
export const LEGAL_CONTACT_EMAIL = 'hello@istockvisual.com';
export const LEGAL_UPDATED = 'August 14, 2026';

export const LEGAL_PAGES = [
	{ href: ABOUT_PATH, label: 'About' },
	{ href: HELP_PATH, label: 'Help' },
	{ href: LICENSE_PATH, label: 'License' },
	{ href: TERMS_PATH, label: 'Terms' },
	{ href: PRIVACY_PATH, label: 'Privacy' },
	{ href: COOKIES_PATH, label: 'Cookies' },
	{ href: REFUNDS_PATH, label: 'Refunds' },
] as const;

export const SITE_BRAND = 'iStockVisual.com';
export const USAGE_TERMS = 'Free for commercial and personal use. Attribution required.';
export const COPYRIGHT_NOTICE =
	'Free to use — commercial and personal use allowed, attribution required.';

const DESC_MAX = 160;

export function assetSearchTitle(imageName: string): string {
	return `STOCK IMAGE OF ${imageName.trim()} free download`;
}

export function assetPageHeading(imageName: string): string {
	return assetSearchTitle(imageName);
}

function stockNoun(category: CategorySlug): string {
	switch (category) {
		case 'illustrations':
			return 'stock illustration';
		case 'vectors':
			return 'stock vector';
		case '3d':
			return 'stock 3D image';
		default:
			return 'stock photo';
	}
}

export function assetSearchDescription(input: {
	title: string;
	shortDescription?: string;
	description?: string;
	category: CategorySlug;
}): string {
	const heading = assetSearchTitle(input.title);
	const lead = (input.shortDescription || input.description || '').trim();
	const closer = 'Royalty-free for commercial use.';

	if (!lead) {
		return clipDescription(`${heading}. ${closer}`);
	}

	const punctuated = /[.!?]$/.test(lead) ? lead : `${lead}.`;
	return clipDescription(`${heading}. ${punctuated} ${closer}`);
}

function clipDescription(text: string): string {
	if (text.length <= DESC_MAX) return text;
	const sliced = text.slice(0, DESC_MAX - 1);
	const lastSpace = sliced.lastIndexOf(' ');
	return `${(lastSpace > 80 ? sliced.slice(0, lastSpace) : sliced).trimEnd()}…`;
}

export function absoluteUrl(pathOrUrl: string, origin: string): string {
	try {
		return new URL(pathOrUrl, origin).href;
	} catch {
		return pathOrUrl;
	}
}

export function stringifyJsonLd(data: unknown): string {
	return JSON.stringify(data).replace(/</g, '\\u003c');
}

export function assetJsonLd(input: {
	origin: string;
	pagePath: string;
	title: string;
	seoTitle: string;
	seoDescription: string;
	imageDescription?: string;
	imageUrl?: string;
	thumbnailUrl?: string;
	width?: number;
	height?: number;
	fileType?: string;
	medium?: string;
	tags?: string[];
	publishedAt?: string;
	categorySlug: CategorySlug;
	categoryLabel: string;
	contentCategories?: string[];
}): Record<string, unknown> {
	const pageUrl = absoluteUrl(input.pagePath, input.origin);
	const homeUrl = `${input.origin}/`;
	const licenseUrl = absoluteUrl(LICENSE_PATH, input.origin);
	const imageId = `${pageUrl}#image`;
	const breadcrumbId = `${pageUrl}#breadcrumb`;
	const websiteId = `${input.origin}/#website`;
	const orgId = `${input.origin}/#organization`;
	const imageUrl = input.imageUrl ? absoluteUrl(input.imageUrl, input.origin) : undefined;
	const thumbnailUrl = input.thumbnailUrl
		? absoluteUrl(input.thumbnailUrl, input.origin)
		: imageUrl;
	const encodingFormat =
		input.fileType && input.fileType.includes('/')
			? input.fileType
			: input.fileType
				? `image/${input.fileType.replace(/^\./, '')}`
				: 'image/jpeg';
	const imageDescription = (
		input.imageDescription ||
		input.seoDescription ||
		input.title
	).trim();

	const organization = {
		'@type': 'Organization',
		'@id': orgId,
		name: SITE_BRAND,
		url: homeUrl,
	};

	const imageObject: Record<string, unknown> = {
		'@type': ['ImageObject', 'VisualArtwork'],
		'@id': imageId,
		name: input.title,
		description: imageDescription,
		contentUrl: imageUrl,
		thumbnailUrl,
		license: licenseUrl,
		acquireLicensePage: licenseUrl,
		copyrightNotice: COPYRIGHT_NOTICE,
		creator: organization,
		creditText: `Generated by ${SITE_BRAND}`,
		encodingFormat,
		usageTerms: USAGE_TERMS,
		isAccessibleForFree: true,
		isFamilyFriendly: true,
		representativeOfPage: true,
	};

	if (input.width) imageObject.width = input.width;
	if (input.height) imageObject.height = input.height;
	if (input.medium) imageObject.artform = input.medium;
	if (input.tags?.length) imageObject.keywords = input.tags.join(', ');
	if (input.publishedAt) {
		imageObject.datePublished = input.publishedAt;
		imageObject.uploadDate = input.publishedAt;
	}

	const crumbs: Array<{ '@type': string; position: number; name: string; item: string }> = [
		{ '@type': 'ListItem', position: 1, name: 'Home', item: homeUrl },
		{
			'@type': 'ListItem',
			position: 2,
			name: input.categoryLabel,
			item: absoluteUrl(`/${input.categorySlug}`, input.origin),
		},
	];

	for (const label of input.contentCategories || []) {
		crumbs.push({
			'@type': 'ListItem',
			position: crumbs.length + 1,
			name: label,
			item: absoluteUrl(contentCategoryPath(label), input.origin),
		});
	}

	crumbs.push({
		'@type': 'ListItem',
		position: crumbs.length + 1,
		name: input.title,
		item: pageUrl,
	});

	return {
		'@context': 'https://schema.org',
		'@graph': [
			organization,
			{
				'@type': 'WebSite',
				'@id': websiteId,
				name: SITE_BRAND,
				url: homeUrl,
				publisher: { '@id': orgId },
			},
			{
				'@type': 'WebPage',
				'@id': pageUrl,
				url: pageUrl,
				name: input.seoTitle,
				description: input.seoDescription,
				inLanguage: 'en',
				isPartOf: { '@id': websiteId },
				primaryImageOfPage: { '@id': imageId },
				breadcrumb: { '@id': breadcrumbId },
			},
			{
				'@type': 'BreadcrumbList',
				'@id': breadcrumbId,
				itemListElement: crumbs,
			},
			imageObject,
		],
	};
}
