import { LEGAL_CONTACT_EMAIL, SITE_BRAND } from './seo';

export type SupportRole = 'user' | 'assistant';
export type SupportMessage = { role: SupportRole; content: string };

type GeminiEnv = {
	GEMINI_API_KEY?: string;
	GEMINI_MODEL?: string;
};

const DEFAULT_MODEL = 'gemini-3.6-flash';
const CONTACT = LEGAL_CONTACT_EMAIL;

const KNOWLEDGE = `
You are the free customer-support assistant for ${SITE_BRAND} (iStockVisual).
Answer only from this knowledge. If you are not sure, say so and point to ${CONTACT}.
Reply in the same language as the customer. Keep answers short and practical. Use plain links as paths like /price, /info/license.

Site: stock photos, illustrations, vectors, and 3D stills, plus in-browser studio tools.
Library content is licensed, not sold, and not public domain. Download does not transfer copyright.

License: commercial and personal use allowed. Attribution required on every size, including Pro.
Credit: "Generated by ${SITE_BRAND}". A link to the image page is preferred when the medium allows it.
Do not resell original or lightly modified files as stock. Do not claim exclusive ownership.

Sizes: 500 and 1K are free. 2K, 4K, and 8K need an active Pro plan or pass. Formats: JPG, PNG, WEBP, SVG. Same license for every size.

Plans (USD, one-time, no auto-renew):
- Free: 500 and 1K
- 1-Day Pass $5.99, 7-Day Pass $11.99, 1-Month Pro $19.99
- 6-Month Pro $49.99, 12-Month Pro $79.99, Lifetime Access $119.99 (launch price; listed original $299.99)
Lifetime is a one-time payment for Pro downloads as long as the library operates.

Fair use: first 100 HD (2K/4K/8K) downloads each day unrestricted; after that 10 HD downloads per hour.

Refunds: 7-day money-back on every paid plan including Lifetime. Email ${CONTACT} from the account address within 7 days with account email, plan, and purchase date. /info/refunds

Accounts: email + password. Sign up at /signup, log in at /login, account at /account.
Pricing: /price

Studio tools (files stay in the browser unless noted): /tools/image editor, /tools/convert, /tools/vectorize, /tools/social resizer, /tools/watermark, /tools/palette.
Visual search: upload a query photo from the search bar. That photo is stored briefly and deleted after about one hour. /info/privacy

Search and filters: text search /s/, categories /c/, type, orientation, color (matched to each image palette; nearest colors if no exact hex), exclude keywords.

Contact: ${CONTACT}
Policies: /info/about /info/license /info/terms /info/privacy /info/cookies /info/refunds /info/help
`.trim();

type Faq = { keys: string[]; answer: string };

const FAQS: Faq[] = [
	{
		keys: ['free', 'cost', 'price', 'pay', '500', '1k', 'download'],
		answer: `500 and 1K downloads are free. 2K, 4K, and 8K need Pro. See /price. Attribution is still required: Generated by ${SITE_BRAND}.`,
	},
	{
		keys: ['pro', 'plan', 'lifetime', 'subscription', 'renew', 'pricing'],
		answer:
			'Pro plans are one-time charges with no auto-renew. Short-term: 1-Day $5.99, 7-Day $11.99, 1-Month $19.99. Long-term: 6-Month $49.99, 12-Month $79.99, Lifetime $119.99. Details: /price.',
	},
	{
		keys: ['license', 'commercial', 'attribution', 'credit', 'copyright'],
		answer: `Library images are free for commercial and personal use. You must credit “Generated by ${SITE_BRAND}”. Full terms: /info/license.`,
	},
	{
		keys: ['refund', 'money back', 'cancel', 'guarantee'],
		answer: `Every paid plan has a 7-day money-back guarantee, including Lifetime. Email ${CONTACT} from your account address within 7 days. Policy: /info/refunds.`,
	},
	{
		keys: ['account', 'signup', 'login', 'password', 'sign in'],
		answer: 'Create an account at /signup and sign in at /login. Use /account to manage your profile and plan.',
	},
	{
		keys: ['tool', 'editor', 'convert', 'vector', 'watermark', 'palette', 'resize'],
		answer:
			'Studio tools run in your browser: Image Editor /tools/image, Convert /tools/convert, Vectorizer /tools/vectorize, Social Resizer /tools/social, Watermark /tools/watermark, Palette /tools/palette. Your device files are not uploaded unless you use visual search.',
	},
	{
		keys: ['search', 'upload', 'image search', 'visual'],
		answer:
			'Use the search bar for keywords, or the image button to search by photo. Query photos for visual search are deleted after about one hour.',
	},
	{
		keys: ['color', 'palette', 'hex', 'filter'],
		answer:
			'The catalog color picker matches each image’s palette. Exact hex matches show first, then closer colors. If nothing matches exactly, we show the nearest palette colors.',
	},
	{
		keys: ['fair use', 'limit', 'cap', 'hour', 'scrap'],
		answer:
			'The first 100 high-resolution (2K / 4K / 8K) downloads each day are unrestricted. After that, a cap of 10 HD downloads per hour applies.',
	},
	{
		keys: ['contact', 'email', 'support', 'help', 'human'],
		answer: `This chat is free automated help. For billing, refunds, or anything we cannot answer, email ${CONTACT}.`,
	},
	{
		keys: ['svg', 'png', 'jpg', 'webp', 'format', 'size', '4k', '8k', '2k'],
		answer:
			'Files come as JPG, PNG, WEBP, or SVG depending on the asset. 500 and 1K are free; 2K, 4K, and 8K need Pro. The same license applies to every size.',
	},
];

function tokens(text: string) {
	return text
		.toLowerCase()
		.replace(/[^\p{L}\p{N}]+/gu, ' ')
		.split(/\s+/)
		.filter((word) => word.length > 1);
}

export function faqAnswer(question: string): string | null {
	const words = new Set(tokens(question));
	if (!words.size) return null;
	let best: { score: number; answer: string } | null = null;
	for (const faq of FAQS) {
		let score = 0;
		for (const key of faq.keys) {
			const parts = key.split(' ');
			if (parts.every((part) => words.has(part)) || question.toLowerCase().includes(key)) score += 2;
			else if (parts.some((part) => words.has(part))) score += 1;
		}
		if (!best || score > best.score) best = { score, answer: faq.answer };
	}
	if (!best || best.score < 2) return null;
	return best.answer;
}

function resolveKey(env: GeminiEnv) {
	return (
		env.GEMINI_API_KEY ||
		(typeof import.meta !== 'undefined' ? (import.meta.env?.GEMINI_API_KEY as string | undefined) : '') ||
		''
	).trim();
}

function resolveModel(env: GeminiEnv) {
	return (
		env.GEMINI_MODEL ||
		(typeof import.meta !== 'undefined' ? (import.meta.env?.GEMINI_MODEL as string | undefined) : '') ||
		DEFAULT_MODEL
	);
}

async function askGemini(env: GeminiEnv, messages: SupportMessage[]): Promise<string | null> {
	const apiKey = resolveKey(env);
	if (!apiKey) return null;
	const model = resolveModel(env);
	const contents = messages
		.filter((item) => item.content.trim())
		.slice(-12)
		.map((item) => ({
			role: item.role === 'assistant' ? 'model' : 'user',
			parts: [{ text: item.content.trim().slice(0, 800) }],
		}));
	if (!contents.length || contents[contents.length - 1]?.role !== 'user') return null;
	if (contents[0].role !== 'user') contents.unshift({ role: 'user', parts: [{ text: 'Hello' }] });

	const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;
	const ac = new AbortController();
	const timer = setTimeout(() => ac.abort(), 20000);
	try {
		const res = await fetch(url, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			signal: ac.signal,
			body: JSON.stringify({
				systemInstruction: { parts: [{ text: KNOWLEDGE }] },
				contents,
				generationConfig: { temperature: 0.35, maxOutputTokens: 420 },
			}),
		});
		const data = (await res.json()) as {
			candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
			error?: { message?: string };
		};
		if (!res.ok) return null;
		const text = (data.candidates?.[0]?.content?.parts || [])
			.map((part) => part.text || '')
			.join('\n')
			.trim();
		return text || null;
	} catch {
		return null;
	} finally {
		clearTimeout(timer);
	}
}

export async function answerSupportChat(
	env: GeminiEnv,
	messages: SupportMessage[],
): Promise<{ reply: string; source: 'ai' | 'faq' }> {
	const last = [...messages].reverse().find((item) => item.role === 'user')?.content || '';
	const ai = await askGemini(env, messages);
	if (ai) return { reply: ai, source: 'ai' };
	const faq = faqAnswer(last);
	if (faq) return { reply: faq, source: 'faq' };
	return {
		reply: `I don’t have a confident answer for that. Email ${CONTACT} and we will help.`,
		source: 'faq',
	};
}

export const SUPPORT_GREETING = `Hi — I’m the free iStockVisual assistant. Ask about licenses, free vs Pro sizes, plans, refunds, or studio tools. For account-specific billing, email ${CONTACT}.`;

export const SUPPORT_PROMPTS = [
	'Is 1K really free?',
	'How do I credit an image?',
	'What does Pro include?',
	'How do refunds work?',
];
