import knowledgeRaw from '../data/support-knowledge.txt?raw';
import { LEGAL_CONTACT_EMAIL, SITE_BRAND } from './seo';

export type SupportRole = 'user' | 'assistant';
export type SupportMessage = { role: SupportRole; content: string };
export type SupportSource = 'gemma' | 'gemini' | 'faq';

type SupportEnv = {
	TOGETHER_API_KEY?: string;
	TOGETHER_MODEL?: string;
	GEMINI_API_KEY?: string;
	GEMINI_MODEL?: string;
};

const CONTACT = LEGAL_CONTACT_EMAIL;
const GEMMA_MODEL = 'google/gemma-4-31B-it';
const GEMINI_MODEL = 'gemini-3.6-flash';

const SYSTEM_PROMPT = `You are the free customer-support assistant for ${SITE_BRAND} (iStockVisual).
Answer ONLY from the internal brief below. If the brief does not cover the question, say you are not sure and give ${CONTACT}.
Do not invent prices, plans, legal terms, or features. Do not browse the web. Do not role-play as a human agent who can edit accounts.
Keep answers short. Prefer bullet points for plans or steps. Include relevant paths (/price, /info/license, /info/refunds).

INTERNAL BRIEF:
${knowledgeRaw.trim()}`.trim();

type Faq = { keys: string[]; answer: string };

const FAQS: Faq[] = [
	{
		keys: ['free', 'cost', 'price', 'pay', '500', '1k', 'download'],
		answer: `500 and 1K downloads are free. 2K, 4K, and 8K need Pro. See /price. Attribution is still required: Generated by ${SITE_BRAND}.`,
	},
	{
		keys: ['pro', 'plan', 'lifetime', 'subscription', 'renew', 'pricing'],
		answer:
			'Pro plans are one-time charges with no auto-renew. Short-term: 1-Day $5.99, 7-Day $11.99, 1-Month $19.99. Long-term: 6-Month $49.99, 12-Month $79.99, Lifetime $119.99. Details: /price.',
	},
	{
		keys: ['license', 'commercial', 'attribution', 'credit', 'copyright'],
		answer: `Library images are free for commercial and personal use. You must credit “Generated by ${SITE_BRAND}”. Full terms: /info/license.`,
	},
	{
		keys: ['refund', 'money back', 'cancel', 'guarantee'],
		answer: `Every paid plan has a 7-day money-back guarantee, including Lifetime. Email ${CONTACT} from your account address within 7 days. Policy: /info/refunds.`,
	},
	{
		keys: ['account', 'signup', 'login', 'password', 'sign in'],
		answer: 'Create an account at /signup and sign in at /login. Use /account to manage your profile and plan.',
	},
	{
		keys: ['tool', 'editor', 'convert', 'vector', 'watermark', 'palette', 'resize'],
		answer:
			'Studio tools run in your browser: Image Editor /tools/image, Convert /tools/convert, Vectorizer /tools/vectorize, Social Resizer /tools/social, Watermark /tools/watermark, Palette /tools/palette. Your device files are not uploaded unless you use visual search.',
	},
	{
		keys: ['search', 'upload', 'image search', 'visual'],
		answer:
			'Use the search bar for keywords, or the image button to search by photo. Query photos for visual search are deleted after about one hour.',
	},
	{
		keys: ['color', 'palette', 'hex', 'filter'],
		answer:
			'The catalog color picker matches each image’s palette. Exact hex matches show first, then closer colors. If nothing matches exactly, we show the nearest palette colors.',
	},
	{
		keys: ['fair use', 'limit', 'cap', 'hour', 'scrap'],
		answer:
			'The first 100 high-resolution (2K / 4K / 8K) downloads each day are unrestricted. After that, a cap of 10 HD downloads per hour applies.',
	},
	{
		keys: ['contact', 'email', 'support', 'help', 'human'],
		answer: `This chat is free automated help. For billing, refunds, or anything we cannot answer, email ${CONTACT}.`,
	},
	{
		keys: ['svg', 'png', 'jpg', 'webp', 'format', 'size', '4k', '8k', '2k'],
		answer:
			'Files come as JPG, PNG, WEBP, or SVG depending on the asset. 500 and 1K are free; 2K, 4K, and 8K need Pro. The same license applies to every size.',
	},
];

function tokens(text: string) {
	return text
		.toLowerCase()
		.replace(/[^\p{L}\p{N}]+/gu, ' ')
		.split(/\s+/)
		.filter((word) => word.length > 1);
}

export function faqAnswer(question: string): string | null {
	const words = new Set(tokens(question));
	if (!words.size) return null;
	let best: { score: number; answer: string } | null = null;
	for (const faq of FAQS) {
		let score = 0;
		for (const key of faq.keys) {
			const parts = key.split(' ');
			if (parts.every((part) => words.has(part)) || question.toLowerCase().includes(key)) score += 2;
			else if (parts.some((part) => words.has(part))) score += 1;
		}
		if (!best || score > best.score) best = { score, answer: faq.answer };
	}
	if (!best || best.score < 2) return null;
	return best.answer;
}

function envString(env: SupportEnv, key: keyof SupportEnv) {
	const fromEnv = env[key];
	const fromMeta =
		typeof import.meta !== 'undefined' ? (import.meta.env?.[key] as string | undefined) : '';
	return (fromEnv || fromMeta || '').trim();
}

function chatTurns(messages: SupportMessage[]) {
	return messages
		.filter((item) => item.content.trim())
		.slice(-12)
		.map((item) => ({
			role: item.role === 'assistant' ? ('assistant' as const) : ('user' as const),
			content: item.content.trim().slice(0, 800),
		}));
}

function cleanModelText(text: string) {
	return text
		.replace(/<think>[\s\S]*?<\/think>/gi, '')
		.replace(/^```(?:\w+)?\s*|\s*```$/g, '')
		.trim();
}

async function askGemma(env: SupportEnv, messages: SupportMessage[]): Promise<string | null> {
	const apiKey = envString(env, 'TOGETHER_API_KEY');
	if (!apiKey) return null;
	const model = envString(env, 'TOGETHER_MODEL') || GEMMA_MODEL;
	const turns = chatTurns(messages);
	if (!turns.length || turns[turns.length - 1]?.role !== 'user') return null;

	const ac = new AbortController();
	const timer = setTimeout(() => ac.abort(), 25000);
	try {
		const res = await fetch('https://api.together.xyz/v1/chat/completions', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${apiKey}`,
			},
			signal: ac.signal,
			body: JSON.stringify({
				model,
				messages: [{ role: 'system', content: SYSTEM_PROMPT }, ...turns],
				temperature: 0.25,
				max_tokens: 480,
				enable_thinking: false,
				chat_template_kwargs: { enable_thinking: false },
			}),
		});
		const data = (await res.json()) as {
			choices?: Array<{
				message?: { content?: string; reasoning?: string; reasoning_content?: string };
			}>;
		};
		if (!res.ok) return null;
		const message = data.choices?.[0]?.message;
		const text = cleanModelText(message?.content || '');
		return text || null;
	} catch {
		return null;
	} finally {
		clearTimeout(timer);
	}
}

async function askGemini(env: SupportEnv, messages: SupportMessage[]): Promise<string | null> {
	const apiKey = envString(env, 'GEMINI_API_KEY');
	if (!apiKey) return null;
	const model = envString(env, 'GEMINI_MODEL') || GEMINI_MODEL;
	const contents = chatTurns(messages).map((item) => ({
		role: item.role === 'assistant' ? 'model' : 'user',
		parts: [{ text: item.content }],
	}));
	if (!contents.length || contents[contents.length - 1]?.role !== 'user') return null;
	if (contents[0].role !== 'user') contents.unshift({ role: 'user', parts: [{ text: 'Hello' }] });

	const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;
	const ac = new AbortController();
	const timer = setTimeout(() => ac.abort(), 20000);
	try {
		const res = await fetch(url, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			signal: ac.signal,
			body: JSON.stringify({
				systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] },
				contents,
				generationConfig: { temperature: 0.25, maxOutputTokens: 420 },
			}),
		});
		const data = (await res.json()) as {
			candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
		};
		if (!res.ok) return null;
		const text = (data.candidates?.[0]?.content?.parts || [])
			.map((part) => part.text || '')
			.join('\n')
			.trim();
		return text || null;
	} catch {
		return null;
	} finally {
		clearTimeout(timer);
	}
}

export async function answerSupportChat(
	env: SupportEnv,
	messages: SupportMessage[],
): Promise<{ reply: string; source: SupportSource }> {
	const last = [...messages].reverse().find((item) => item.role === 'user')?.content || '';
	const gemma = await askGemma(env, messages);
	if (gemma) return { reply: gemma, source: 'gemma' };
	const gemini = await askGemini(env, messages);
	if (gemini) return { reply: gemini, source: 'gemini' };
	const faq = faqAnswer(last);
	if (faq) return { reply: faq, source: 'faq' };
	return {
		reply: `I don’t have a confident answer for that. Email ${CONTACT} and we will help.`,
		source: 'faq',
	};
}
