import { useEffect, useMemo, useRef, useState } from 'react';
import {
	DOWNLOAD_FORMATS,
	convertDownloadBlob,
	downloadFileLabel,
	scaleDownloadBlob,
	type DownloadFormat,
} from '../lib/download-formats';
import {
	DOWNLOAD_SIZES,
	fetchSizeForDownload,
	isFreeDownloadSize,
	outputSizeForDownload,
	type DownloadSizeId,
} from '../lib/download-sizes';
import { LONG_PLANS } from '../lib/pricing';
import { LICENSE_PATH, SITE_BRAND } from '../lib/seo';

type Props = {
	assetId: string;
	title: string;
	slug: string;
	previewUrl?: string;
	sourceWidth?: number;
	sourceHeight?: number;
	loggedIn: boolean;
	isPro: boolean;
	loginHref: string;
	signupHref?: string;
	upgradeHref?: string;
	pageUrl?: string;
};

function triggerDownload(blob: Blob, filename: string) {
	const url = URL.createObjectURL(blob);
	const link = document.createElement('a');
	link.href = url;
	link.download = filename;
	document.body.appendChild(link);
	link.click();
	link.remove();
	window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}

function CrownIcon() {
	return (
		<svg className="download-pro-icon" viewBox="0 0 16 16" width="12" height="12" aria-hidden="true">
			<path
				fill="currentColor"
				d="M1.5 12.5h13v1.2H1.5zm.8-7.2 2.7 2.1L8 3.2l2.9 4.2 2.8-2.1.7 7H1.6z"
			/>
		</svg>
	);
}

function ChevronIcon() {
	return (
		<svg className="download-split__chevron" viewBox="0 0 16 16" width="14" height="14" aria-hidden="true">
			<path fill="currentColor" d="M3.2 5.6 8 10.4l4.8-4.8 1.1 1.1L8 12.6 2.1 6.7z" />
		</svg>
	);
}

function DownloadIcon() {
	return (
		<svg className="download-split__icon" viewBox="0 0 24 24" width="20" height="20" aria-hidden="true">
			<path
				d="M12 3.6v11.2"
				fill="none"
				stroke="currentColor"
				strokeWidth="2.2"
				strokeLinecap="round"
			/>
			<path
				d="M7 11.2 12 16.2 17 11.2"
				fill="none"
				stroke="currentColor"
				strokeWidth="2.2"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
			<path
				d="M4.6 17.4v1.4A2.2 2.2 0 0 0 6.8 21h10.4a2.2 2.2 0 0 0 2.2-2.2v-1.4"
				fill="none"
				stroke="currentColor"
				strokeWidth="2.2"
				strokeLinecap="round"
			/>
		</svg>
	);
}

function CheckIcon() {
	return (
		<svg viewBox="0 0 16 16" width="12" height="12" aria-hidden="true">
			<path
				d="M3.2 8.2 6.5 11.4 12.8 4.6"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.7"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

function LinkIcon() {
	return (
		<svg viewBox="0 0 16 16" width="12" height="12" aria-hidden="true">
			<path
				d="M6.4 9.6a2.6 2.6 0 0 1 0-3.7l1.6-1.6a2.6 2.6 0 1 1 3.7 3.7L10.6 9.1"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.5"
				strokeLinecap="round"
			/>
			<path
				d="M9.6 6.4a2.6 2.6 0 0 1 0 3.7L8 11.7a2.6 2.6 0 1 1-3.7-3.7l1.1-1.1"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.5"
				strokeLinecap="round"
			/>
		</svg>
	);
}

const ATTR_FORMATS = [
	{ id: 'html-title', label: 'HTML with title' },
	{ id: 'html-view', label: 'HTML with view original' },
	{ id: 'html-paren', label: 'HTML parenthetical' },
	{ id: 'html-source', label: 'HTML source format' },
	{ id: 'markdown', label: 'Markdown' },
	{ id: 'plain', label: 'Plain text' },
] as const;

type AttrFormatId = (typeof ATTR_FORMATS)[number]['id'];

function escapeHtml(value: string) {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

function attributionSnippet(format: AttrFormatId, title: string, url: string) {
	const safeTitle = escapeHtml(title);
	switch (format) {
		case 'html-title':
			return `<a href="${url}">${safeTitle}</a>`;
		case 'html-view':
			return `${safeTitle} — <a href="${url}">view original</a>`;
		case 'html-paren':
			return `(<a href="${url}">${safeTitle}</a>)`;
		case 'html-source':
			return `Source: <a href="${url}">${SITE_BRAND}</a>`;
		case 'markdown':
			return `[${title}](${url})`;
		case 'plain':
			return `${title} — Generated by ${SITE_BRAND} ${url}`;
	}
}

function HeartIcon() {
	return (
		<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true">
			<path
				d="M12 20.4S4.2 15.4 2.4 11.2C.7 7.4 2.6 3.6 6.6 3.4c2.2-.1 3.9 1.1 5.4 3.1 1.5-2 3.2-3.2 5.4-3.1 4 .2 5.9 4 4.2 7.8-1.8 4.2-9.6 9.2-9.6 9.2Z"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.7"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

function GlobeIcon() {
	return (
		<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true">
			<circle cx="12" cy="12" r="8.2" fill="none" stroke="currentColor" strokeWidth="1.6" />
			<path
				d="M3.8 12h16.4M12 3.8c2.4 2.4 3.6 5.2 3.6 8.2s-1.2 5.8-3.6 8.2c-2.4-2.4-3.6-5.2-3.6-8.2s1.2-5.8 3.6-8.2Z"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.5"
			/>
		</svg>
	);
}

function CopySquaresIcon() {
	return (
		<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
			<rect x="5.5" y="5.5" width="8" height="8" rx="1.2" fill="none" stroke="currentColor" strokeWidth="1.4" />
			<path
				d="M3.5 10.5h-1A1.5 1.5 0 0 1 1 9V3.5A1.5 1.5 0 0 1 2.5 2H8a1.5 1.5 0 0 1 1.5 1.5v1"
				fill="none"
				stroke="currentColor"
				strokeWidth="1.4"
			/>
		</svg>
	);
}

function ShareLoveModal({
	title,
	pageUrl,
	onClose,
}: {
	title: string;
	pageUrl: string;
	onClose: () => void;
}) {
	const [format, setFormat] = useState<AttrFormatId>('html-title');
	const [formatOpen, setFormatOpen] = useState(false);
	const [copied, setCopied] = useState(false);
	const formatRef = useRef<HTMLDivElement>(null);
	const snippet = attributionSnippet(format, title, pageUrl);
	const formatLabel = ATTR_FORMATS.find((item) => item.id === format)?.label ?? 'HTML with title';

	useEffect(() => {
		const onPointer = (event: MouseEvent) => {
			if (!formatRef.current?.contains(event.target as Node)) setFormatOpen(false);
		};
		window.addEventListener('mousedown', onPointer);
		return () => window.removeEventListener('mousedown', onPointer);
	}, []);

	async function copySnippet() {
		try {
			await navigator.clipboard.writeText(snippet);
			setCopied(true);
			window.setTimeout(() => setCopied(false), 1400);
		} catch {
			setCopied(false);
		}
	}

	return (
		<div className="download-auth-modal" role="presentation">
			<button
				type="button"
				className="download-auth-modal__backdrop"
				aria-label="Close"
				onClick={onClose}
			/>
			<div
				className="download-auth-modal__dialog share-love"
				role="dialog"
				aria-modal="true"
				aria-labelledby="share-love-title"
			>
				<button type="button" className="download-auth-modal__close" aria-label="Close" onClick={onClose}>
					×
				</button>
				<header className="share-love__head">
					<span className="share-love__heart">
						<HeartIcon />
					</span>
					<h2 id="share-love-title">Credit this image</h2>
				</header>
				<div className="share-love__banner">
					<GlobeIcon />
					<div>
						<strong>Free for commercial work</strong>
						<p>A short credit keeps iStockVisual available to everyone.</p>
					</div>
				</div>
				<label className="share-love__label" htmlFor="share-love-format">
					Choose a credit format
				</label>
				<div className="share-love__select" ref={formatRef}>
					<button
						id="share-love-format"
						type="button"
						className={`share-love__trigger${formatOpen ? ' is-open' : ''}`}
						aria-haspopup="listbox"
						aria-expanded={formatOpen}
						onClick={() => setFormatOpen((open) => !open)}
					>
						{formatLabel}
						<ChevronIcon />
					</button>
					{formatOpen ? (
						<ul className="share-love__menu" role="listbox" aria-label="Attribution format">
							{ATTR_FORMATS.map((item) => (
								<li key={item.id} role="option" aria-selected={item.id === format}>
									<button
										type="button"
										className={item.id === format ? 'is-selected' : undefined}
										onClick={() => {
											setFormat(item.id);
											setFormatOpen(false);
										}}
									>
										{item.label}
										{item.id === format ? <CheckIcon /> : null}
									</button>
								</li>
							))}
						</ul>
					) : null}
				</div>
				<div className="share-love__snippet">
					<code title={snippet}>{snippet}</code>
					<button
						type="button"
						className={`share-love__copy${copied ? ' is-copied' : ''}`}
						onClick={() => void copySnippet()}
						aria-label={copied ? 'Copied' : 'Copy attribution'}
						title={copied ? 'Copied' : 'Copy'}
					>
						<CopySquaresIcon />
					</button>
				</div>
				<p className="share-love__thanks">Thank you for supporting free AI images!</p>
			</div>
		</div>
	);
}

export default function DownloadPanel({
	assetId,
	title,
	slug,
	previewUrl: _previewUrl,
	sourceWidth = 1536,
	sourceHeight = 1024,
	loggedIn,
	isPro,
	loginHref,
	signupHref = '/signup',
	pageUrl,
}: Props) {
	const [selected, setSelected] = useState<DownloadSizeId>('1k');
	const [menuOpen, setMenuOpen] = useState(false);
	const [busy, setBusy] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [natural, setNatural] = useState({ width: sourceWidth, height: sourceHeight });
	const [authModalOpen, setAuthModalOpen] = useState(false);
	const [plansModalOpen, setPlansModalOpen] = useState(false);
	const [pendingSize, setPendingSize] = useState<string | null>(null);
	const [attrModalOpen, setAttrModalOpen] = useState(false);
	const [pageHref, setPageHref] = useState(pageUrl || '');
	const rootRef = useRef<HTMLDivElement>(null);

	const anyModalOpen = authModalOpen || plansModalOpen || attrModalOpen;

	useEffect(() => {
		if (pageUrl) setPageHref(pageUrl);
		else setPageHref(window.location.href);
	}, [pageUrl]);

	useEffect(() => {
		setNatural({ width: sourceWidth, height: sourceHeight });
	}, [sourceHeight, sourceWidth]);

	useEffect(() => {
		if (!anyModalOpen) return;
		const onKey = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				setAuthModalOpen(false);
				setPlansModalOpen(false);
				setAttrModalOpen(false);
			}
		};
		document.body.classList.add('download-auth-modal-open');
		window.addEventListener('keydown', onKey);
		return () => {
			document.body.classList.remove('download-auth-modal-open');
			window.removeEventListener('keydown', onKey);
		};
	}, [anyModalOpen]);

	useEffect(() => {
		if (!menuOpen) return;
		const onPointer = (event: MouseEvent) => {
			if (!rootRef.current?.contains(event.target as Node)) setMenuOpen(false);
		};
		const onKey = (event: KeyboardEvent) => {
			if (event.key === 'Escape') setMenuOpen(false);
		};
		window.addEventListener('mousedown', onPointer);
		window.addEventListener('keydown', onKey);
		return () => {
			window.removeEventListener('mousedown', onPointer);
			window.removeEventListener('keydown', onKey);
		};
	}, [menuOpen]);

	const sizes = useMemo(
		() =>
			DOWNLOAD_SIZES.map((size) => ({
				...size,
				output: outputSizeForDownload(natural.width, natural.height, size),
			})),
		[natural.height, natural.width],
	);

	function gateSize(sizeId: DownloadSizeId): boolean {
		const size = DOWNLOAD_SIZES.find((item) => item.id === sizeId);
		if (!size) return false;

		if (!isFreeDownloadSize(size.id)) {
			if (!loggedIn) {
				setPendingSize(size.label);
				setMenuOpen(false);
				setAuthModalOpen(true);
				return false;
			}
			if (!isPro) {
				setPendingSize(size.label);
				setMenuOpen(false);
				setPlansModalOpen(true);
				return false;
			}
		}
		return true;
	}

	async function downloadSize(sizeId: DownloadSizeId, format: DownloadFormat = 'jpg') {
		if (!gateSize(sizeId)) return;

		setBusy(true);
		setError(null);
		setSelected(sizeId);
		setMenuOpen(false);

		try {
			const res = await fetch(`/api/download/${assetId}?size=${fetchSizeForDownload(sizeId)}`);
			if (!res.ok) {
				const body = (await res.json().catch(() => null)) as { error?: string } | null;
				throw new Error(body?.error || 'Download failed');
			}
			const source = await res.blob();
			const sized = await scaleDownloadBlob(source, sizeId, natural.width, natural.height);
			const output = await convertDownloadBlob(sized, format);
			triggerDownload(output, downloadFileLabel(slug, sizeId, format));
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Download failed');
		} finally {
			setBusy(false);
		}
	}

	return (
		<div className="download-panel" ref={rootRef}>
			<div className="download-split-wrap">
				<button
					type="button"
					className={`download-split${menuOpen ? ' is-open' : ''}`}
					disabled={busy}
					aria-expanded={menuOpen}
					aria-haspopup="listbox"
					onClick={() => setMenuOpen((open) => !open)}
				>
					<DownloadIcon />
					<span className="download-split__label">
						Download for <em>FREE</em>
					</span>
					<ChevronIcon />
				</button>

				{menuOpen && (
					<ul className="download-menu" role="listbox" aria-label="Download sizes">
						{sizes.map((size, index) => {
							const dims = `${size.output.width} × ${size.output.height}`;
							const needsPro = !isFreeDownloadSize(size.id);
							const prevNeedsPro =
								index > 0 && !isFreeDownloadSize(sizes[index - 1]?.id);
							const isSelected = selected === size.id;
							return (
								<li
									key={size.id}
									role="option"
									aria-selected={isSelected}
									className={`download-menu__row${needsPro && !prevNeedsPro ? ' download-menu__row--pro-start' : ''}`}
								>
									<span className="download-menu__meta">
										{needsPro ? (
											<em className="download-tier download-tier--pro">Pro</em>
										) : (
											<span className="download-tier download-tier--free">Free</span>
										)}
										<span className="download-menu__dims">{dims}</span>
									</span>
									<span className="download-menu__formats">
										{DOWNLOAD_FORMATS.map((format) => (
											<button
												key={format}
												type="button"
												className="download-menu__format"
												disabled={busy}
												onClick={() => void downloadSize(size.id, format)}
											>
												{format.toUpperCase()}
											</button>
										))}
									</span>
								</li>
							);
						})}
					</ul>
				)}
			</div>
			<ul className="download-perks">
				<li>
					<a href={LICENSE_PATH}>
						<CheckIcon />
						Free to use
					</a>
				</li>
				<li>
					<a href={LICENSE_PATH}>
						<CheckIcon />
						Commercial use
					</a>
				</li>
				<li>
					<button
						type="button"
						onClick={() => {
							setMenuOpen(false);
							setAttrModalOpen(true);
						}}
					>
						<LinkIcon />
						Copy attribution
					</button>
				</li>
			</ul>
			{error && <p className="download-panel__error">{error}</p>}

			{attrModalOpen ? (
				<ShareLoveModal
					title={title}
					pageUrl={pageHref || pageUrl || ''}
					onClose={() => setAttrModalOpen(false)}
				/>
			) : null}

			{authModalOpen && (
				<div className="download-auth-modal" role="presentation">
					<button
						type="button"
						className="download-auth-modal__backdrop"
						aria-label="Close"
						onClick={() => setAuthModalOpen(false)}
					/>
					<div
						className="download-auth-modal__dialog"
						role="dialog"
						aria-modal="true"
						aria-labelledby="download-auth-title"
					>
						<button
							type="button"
							className="download-auth-modal__close"
							aria-label="Close"
							onClick={() => setAuthModalOpen(false)}
						>
							×
						</button>
						<p className="download-auth-modal__eyebrow">
							<CrownIcon /> Pro download
						</p>
						<h2 id="download-auth-title">Sign up for {pendingSize || '2K+'} downloads</h2>
						<p>
							500 and 1K are free without logging in. Create an account and upgrade to Pro for
							2K, 4K, and 8K.
						</p>
						<div className="download-auth-modal__actions">
							<a className="btn btn--primary" href={signupHref}>
								Create free account
							</a>
							<a className="btn btn--ghost" href={loginHref}>
								Log in
							</a>
						</div>
					</div>
				</div>
			)}

			{plansModalOpen && (
				<div className="download-auth-modal" role="presentation">
					<button
						type="button"
						className="download-auth-modal__backdrop"
						aria-label="Close"
						onClick={() => setPlansModalOpen(false)}
					/>
					<div
						className="download-auth-modal__dialog download-auth-modal__dialog--plans"
						role="dialog"
						aria-modal="true"
						aria-labelledby="download-plans-title"
					>
						<button
							type="button"
							className="download-auth-modal__close"
							aria-label="Close"
							onClick={() => setPlansModalOpen(false)}
						>
							×
						</button>
						<p className="download-auth-modal__eyebrow">
							<CrownIcon /> Membership
						</p>
						<h2 id="download-plans-title">Unlimited downloads</h2>
						<p>
							{pendingSize
								? `${pendingSize} requires Pro. Choose a plan below, or open the pricing page.`
								: 'Choose a temporary plan. Full details and checkout are on the pricing page.'}
						</p>
						<ul className="download-plan-list">
							{LONG_PLANS.map((plan) => (
								<li key={plan.id}>
									<div>
										<strong>{plan.name}</strong>
										<span>{plan.rate}</span>
									</div>
									<em>{plan.price}</em>
								</li>
							))}
						</ul>
						<div className="download-auth-modal__actions">
							<a className="btn btn--primary" href="/price">
								Details · Pricing page
							</a>
							<button
								type="button"
								className="btn btn--ghost"
								onClick={() => setPlansModalOpen(false)}
							>
								Close
							</button>
						</div>
					</div>
				</div>
			)}
		</div>
	);
}
